"""STR-04 control-plane reconciliation only; preserve all implementation and other rows."""
from pathlib import Path
from collections import Counter
import copy, hashlib, json, re, shutil, subprocess
import xml.etree.ElementTree as ET
import yaml
from trader.strategy import factory_handoff as F

ROOT=Path(__file__).resolve().parents[4]; EP=Path(__file__).resolve().parent; EVID=str(EP.relative_to(ROOT))
HEAD=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip()
assert HEAD.startswith('516638e')
paths={'tracker':'docs/tracker/LUFFY_Product_Tracker_v1.yaml','state':'STATE.yaml','next':'NEXT.yaml'}
docs={k:yaml.safe_load((ROOT/p).read_text()) for k,p in paths.items()}
rows={r['id']:r for r in docs['tracker']['items']}; old=copy.deepcopy(rows['STR-04'])
assert old['status']=='EVIDENCE_TO_MAP' and rows['STR-03']['status']=='CLOSED'
suite=ET.parse(EP/'dedicated.xml').getroot().find('testsuite')
assert int(suite.get('tests'))==70 and all(int(suite.get(k))==0 for k in ['errors','failures','skipped'])
by_class=Counter(x.get('classname') for x in suite.findall('testcase'))
assert by_class['tests.test_str04_governor_lifecycle']==26 and by_class['tests.test_str03_approval_binding']==44
proof=json.loads((EP/'binding-proof.json').read_text()); assert not proof['required_proof_satisfied']
assert not proof['privileged_flag_or_corruption_used']
retained=Path('/tmp/claude-1000/-mnt-luffy-data-luffy-production/2e2bb811-57dd-4d57-892c-fd6f087659e2/scratchpad/reg2.txt')
assert '3 failed, 682 passed' in retained.read_text(); shutil.copyfile(retained,EP/'related-engineering.txt')
counts=dict(Counter(r['status'] for r in rows.values())); counts['EVIDENCE_TO_MAP']-=1; counts['BLOCKED']+=1
source_paths=['trader/strategy/factory_handoff.py','trader/core/journal.py','trader/kernel.py','trader/strategy/promotion.py','trader/brain/strategist.py','trader/brain/tv.py','trader/engine/risk.py','trader/strategy/capacity.py','tests/test_str04_governor_lifecycle.py','tests/test_str03_approval_binding.py','tests/test_universal_strategy_authority.py','config.yaml']
hashes={}
for p in source_paths:
    b=(ROOT/p).read_bytes(); assert b==subprocess.check_output(['git','show',HEAD+':'+p],cwd=ROOT); hashes[p]=hashlib.sha256(b).hexdigest()
record=dict(item='STR-04',canonical_status='BLOCKED',scope='ARCHITECTURE_OFFLINE',engineering_commit='872131f3755ab2d156e9cce73f0deae3b7630df2',control_baseline_revision=HEAD,dependency_STR03_canonical_commit=HEAD,closing_condition=old['closure_condition'],failure_regression_proof=old['failure_regression_proof'],closing_condition_satisfied=False,
 blocker=dict(id='STR04-BINDING-01',required_proof='2. Every new Governor event binds owner decision identity; replay verifies bindings.',finding=proof['blocker'],ordinary_canonical_path=True,privileged_corruption_required=False,from_state='APPROVED_FIRST_LIVE',targets=['PAUSED','DEGRADED','RETIRED'],reproducer=EVID+'/binding-proof.py',evidence=EVID+'/binding-proof.json',cause='The writer initializes owner_decision_id from Governor history or None and only resolves eligibility.decision_id for ACTIVE/REACTIVATED. With no earlier activation, a non-activating event omits the already-existing decision.',required_fix='In a separate authorized engineering task, bind the existing exact owner decision for approved versions even before the first activation, verify the binding on replay, and add regression evidence for these paths.'),
 verified_mapping=dict(sole_authority='govern_version writes Governor events and projects versioned strategies.state. DB triggers refuse lifecycle version events, raw Governor inserts and ungoverned versioned row state edits/deletes/replacements. Other state writers remain legacy-only for versioned ids.',exact_binding='New events carry version/spec, strategy/lineage/install/request binding, transition_id/key and requested allocation. Post-ACTIVE lifecycle events inherit owner decision. First approved non-activation events have the blocking omission.',state_machine='GOVERNOR_ALLOWED below is exact. Dedicated tests verify retired terminality, unapproved activation refusal and stale probation reactivation refusal.',atomicity='Both injected strategies-row UPDATE failure and Governor-event INSERT failure roll back event and projection; retry succeeds after fault removal.',idempotency='Latest duplicate returns identical event; explicit earlier transition key replays prior event, conflicting key refuses; restart retains exact history/state.',projection='ACTIVE/REACTIVATED active; PAUSED/DEGRADED paper; RETIRED retired. Divergence is detected and live_entry_block refuses.',activation='ACTIVE/REACTIVATED consume eligible_for_first_live with exact approval/install/available inputs/current capacity, authoritative same-journal Risk release, matching Risk policy and owner ceiling/risk hash. Full approval config_sha256 is rechecked through STR-03.',immutability='Dedicated snapshot covers versions, validation, install, probation, approval request and decision across full lifecycle. Lifecycle API accepts no spec/lineage/evidence rewrite; same-id spec rewrite blocks live entry; changed semantics derive a new version.',bypass='Dedicated refusal evidence includes raw writes, version-event lifecycle insert, label/grandfather, sibling and stale approval; rewritten installed semantics cannot authorize entry.',execution_boundary='ACTIVE alone preserves version_first_live_execution_not_enabled; Kernel consumes live_entry_block.'),
 allowed_transitions={k:sorted(v) for k,v in F.GOVERNOR_ALLOWED.items()},projection=F.PROJECTION,
 limitations=['Pause/degrade/retire reason strings are bound but not registry-validated.','DB guard is flag-based, not cryptographic protection against privileged code deliberately setting governor_write.','STR-05 owns what evidence may trigger degradation, retirement or recovery.'],
 validation=dict(fresh_STR04_passed=26,fresh_STR03_passed=44,fresh_combined_passed=70,retained_broader_passed=682,retained_broader_failed=3,retained_log=EVID+'/related-engineering.txt',baseline_reproduction='All three failures reproduced identically on clean baseline per user-supplied engineering evidence; clean-baseline log is not independently retained in this package.',failure_ids=['tests/test_stage8_owner_os.py::test_portfolio_exact_cut_candidates_rejection_intent_risk','tests/test_lifecycle_kind_routing.py::test_genome_rows_still_evaluate_normally','tests/test_lifecycle_kind_routing.py::test_spec_and_genome_coexist_in_one_sweep'],full_suite_green_claim=False,counts_overlap_do_not_sum=True,provider_calls=0,full_broader_run_repeated=False),
 dependency_status={'STR-03':'CLOSED'},DEC03_dependencies_satisfied=False,DEC03_now_eligible=False,DEC03_selected=False,DEC03_started=False,DEC03_remaining_blockers=['STR-04'],status_counts_after=counts,original_conditions_and_edges_preserved=True,unrelated_rows_unchanged=177,source_sha256=hashes,application_code_changed=False,runtime_execution_authorized=False,provider_enablement_authorized=False,trading_activation_authorized=False,control_plane_commit_resolution='Enclosing Git commit containing this record; no self-referential hash.')
(EP/'reconciliation.json').write_text(json.dumps(record,indent=2)+'\n')
row=copy.deepcopy(old); row.update(status='BLOCKED',implementation_evidence='Governor lifecycle implementation at 872131f; verified source bytes pinned to '+HEAD+'. '+EVID+'/reconciliation.json',runtime_evidence='ARCHITECTURE_OFFLINE_ONLY; synthetic journals, no deployed/live/provider claim',latest_evidence='26 STR-04 + 44 STR-03 tests passed. Required owner-decision binding fails for APPROVED_FIRST_LIVE -> PAUSED/DEGRADED/RETIRED as the first Governor action: owner_decision_id is null despite an existing decision, and replay accepts it. Ordinary canonical writer, no privileged corruption. Retained broader run 682 passed / 3 identical clean-baseline failures per supplied evidence. '+EVID+'/binding-proof.json',next_proof=record['blocker']['required_fix']+' DEC-03 remains gated, unselected and unstarted.',resolution_at_commit=HEAD,implementation_commit=record['engineering_commit'],updated='2026-10-07',closure_evidence=EVID+'/reconciliation.json',evidence_mapping=EVID+'/REPORT.md',evidence_validity='Pinned offline verification at '+HEAD+'; required event owner binding remains unsatisfied; no later runtime claim.',blocker_evidence=EVID+'/binding-proof.json')
def block(text,key,value):
    m=re.search(r'(?m)^'+re.escape(key)+r':\n',text); assert m,key
    end=re.search(r'(?m)^[A-Za-z_][A-Za-z0-9_]*:',text[m.end():]); stop=m.end()+end.start() if end else len(text)
    return text[:m.start()]+yaml.safe_dump({key:value},sort_keys=False,allow_unicode=True,width=105)+'\n'+text[stop:]
sel=copy.deepcopy(docs['tracker']['current_build_selection']); sel.update(next_recommended_item='STR-04',last_terminal_item='STR-04',last_terminal_result='BLOCKED_ARCHITECTURE_OFFLINE',selection_reason='STR-04 canonical reconciliation BLOCKED on STR04-BINDING-01: initial approved non-activation events omit owner decision identity. STR-03 remains CLOSED. DEC-03 dependencies are not satisfied; DEC-03 is not eligible, selected or started. Next action is a separate STR-04 engineering fix; this reconciliation authorizes no implementation or runtime work.')
sel['eligible_items']=[x for x in sel['eligible_items'] if x!='STR-04']; sel['current_blocked_items']+=['STR-04']
meta=copy.deepcopy(docs['tracker']['metadata']); meta.update(version='1.54-str04-canonical-blocked-sol1',current_active_item='STR-04',current_active_result='BLOCKED_ARCHITECTURE_OFFLINE',last_terminal_item='STR-04',last_terminal_result='BLOCKED_ARCHITECTURE_OFFLINE',last_terminal_evidence=EVID+'/REPORT.md',next_recommended_item='STR-04',status_counts=counts)
p=ROOT/paths['tracker']; text=p.read_text(); a=text.index('- id: STR-04\n'); b=text.index('- id: STR-05\n',a); text=text[:a]+yaml.safe_dump([row],sort_keys=False,allow_unicode=True,width=105)+text[b:]; text=block(text,'metadata',meta); text=block(text,'current_build_selection',sel); text+='\n'+yaml.safe_dump({'str04_canonical_reconciliation':record},sort_keys=False,allow_unicode=True,width=105); p.write_text(text.rstrip()+'\n')
package=dict(id='STR-04',status='BLOCKED',result='BLOCKED_ARCHITECTURE_OFFLINE',mode='ENGINEERING_ONLY',scope='ARCHITECTURE_OFFLINE',objective=old['required_behavior'],implementation_commit=record['engineering_commit'],verification_revision=HEAD,evidence=[EVID+'/REPORT.md',EVID+'/reconciliation.json',EVID+'/binding-proof.json'],implementation_complete=False,canonical_reconciliation_pending=False,closing_condition_satisfied=False,runtime_execution_authorized=False,provider_enablement_authorized=False,trading_activation_authorized=False,successor_selected=False,next_action=record['blocker']['required_fix'])
for name,key in [('state','current_active_work'),('next','work_package')]:
    p=ROOT/paths[name]; text=block(p.read_text(),key,package); text=block(text,'current_build_selection',sel); text+='\n'+yaml.safe_dump({'str04_previous_selection':docs[name][key],'str04_canonical_reconciliation':record},sort_keys=False,allow_unicode=True,width=105); p.write_text(text.rstrip()+'\n')
banner='> Current [SOL-1][STR-04]: **BLOCKED at architecture/offline scope**. Initial approved PAUSED/DEGRADED/RETIRED events omit the existing owner decision identity and replay accepts them. 26 STR-04 + 44 STR-03 dedicated tests pass, but required binding proof fails. STR-03 remains CLOSED; DEC-03 remains gated, unselected and unstarted. [Evidence](evidence/str04-canonical-sol1/REPORT.md). Earlier summaries below are historical.\n\n'
p=ROOT/'docs/tracker/LUFFY_Product_Tracker_v1.md'; text=p.read_text(); a=text.index('### STR-04 —'); b=text.index('### STR-05 —',a); section=text[a:b]
for k,v in row.items():
    if old.get(k)!=v:
        marker='- **'+k+'**: '
        if marker.rstrip() in section: section=re.sub(r'(?m)^'+re.escape(marker.rstrip())+r'.*$',lambda m,k=k,v=v:'- **'+k+'**: '+str(v),section)
        else: section=section.rstrip()+'\n'+marker+str(v)+'\n\n'
p.write_text(banner+text[:a]+section+text[b:]+'\nSTR-04 canonical status counts: '+', '.join(f'{k} {v}' for k,v in counts.items())+' (178 total).\n')
p=ROOT/'docs/tracker/README.md'; p.write_text(banner+p.read_text())
report='# STR-04 canonical BLOCKED\n\nEngineering `872131f`; verification pinned to `'+HEAD+'`. STR-03 is canonically CLOSED at `516638e`.\n\nThe exact condition remains unsatisfied: '+old['closure_condition']+'\n\nRequired proof 2 fails on an ordinary supported path. An approved version with an exact owner decision can take its first Governor transition directly to PAUSED, DEGRADED or RETIRED. All three new events store `owner_decision_id: null`; `governor_events` replays them successfully. The approval request is bound, but its owner decision is not. The writer takes the decision from prior Governor history and only resolves the current decision for ACTIVE/REACTIVATED. This is independent of the privileged-writer limitation: the reproducer sets no internal flag, drops no guard and rewrites no event. See [reproducer](binding-proof.py) and [results](binding-proof.json).\n\nThe 26 dedicated STR-04 tests and 44 STR-03 tests passed together (70 total). Existing lifecycle tests exercise pause/degrade/retire after ACTIVE, which already supplies owner decision identity. They do not cover the failing approved pre-ACTIVE paths.\n\n'
for k,v in record['verified_mapping'].items(): report+='**'+k.replace('_',' ').capitalize()+'.** '+v+'\n\n'
report+='Exact allowed transition matrix (all other transitions refuse):\n\n| From | Allowed targets |\n|---|---|\n'
for k,v in record['allowed_transitions'].items(): report+='| '+k+' | '+(', '.join(v) if v else 'None (terminal)')+' |\n'
report+='\nREJECTED has no Governor transitions. Retry may return an already-recorded event without a new transition.\n\nLimitations retained: '+' '.join(record['limitations'])+'\n\nRetained broader engineering log: 682 passed / 3 failed. Identical clean-baseline reproduction is supplied engineering evidence; a separate baseline log is not independently retained here. No full-suite green claim; counts overlap. No live/provider calls or runtime activation.\n\nSTR-04 remains BLOCKED; all 177 other rows, STR-03 closure, original conditions/dependencies, readiness gates and runtime state are preserved. DEC-03 dependencies are not satisfied and it is not eligible, selected or started.\n\nNext action: '+record['blocker']['required_fix']+' Implementation is unchanged by this task.\n\nCounts: '+', '.join(f'{k} {v}' for k,v in counts.items())+' (178 total). Control-plane commit: enclosing Git commit.\n'
(EP/'REPORT.md').write_text(report)
p=ROOT/'docs/tracker/bundle-manifest.json'; m=json.loads(p.read_text()); m.update(snapshot_version=meta['version'],control_baseline_revision=HEAD,current_build_selection=sel,str04_canonical_reconciliation=record)
known={x['path'] for x in m['files']}
for f in sorted(EP.iterdir()):
    rel=str(f.relative_to(ROOT))
    if f.is_file() and rel not in known: m['files'].append(dict(path=rel,role='STR04_CANONICAL_CONTROL_OR_EVIDENCE',synchronization_required=True))
for e in m['files']:
    raw=(ROOT/e['path']).read_bytes(); e.update(bytes=len(raw),sha256=hashlib.sha256(raw).hexdigest())
p.write_text(json.dumps(m,indent=2)+'\n')
print(json.dumps(dict(STR04='BLOCKED',counts=counts),indent=2))
